name: Deploy Package to an Environment
on:
  workflow_dispatch:
    inputs:
      package:
        type: string
      port_payload:
        required: true
        description: Port's payload, including details for who triggered the action and
          general context (blueprint, run id, etc...)
        type: string
jobs:
  deploy_package_to_environment:
    runs-on: ubuntu-latest
    steps:
      - name: Create a log message
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{fromJson(inputs.port_payload).context.runId}}
          logMessage: Starting deployment of package 
          # logMessage: Starting deployment of package => ${{fromJson(inputs.package).package}}
      
      - name: 'run Codefresh pipeline'
        uses: codefresh-io/codefresh-pipeline-runner@v7
        with:
          args: '-v PORT_PAYLOAD=${{fromJson(inputs.port_payload).payload}}'
        env:
          PIPELINE_NAME: 'port-idp/my_promote_pipeline'
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
        id: run-pipeline          
      
      - name: Update action run status
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{fromJson(inputs.port_payload).context.runId}}
          status: SUCCESS
          # logMessage: COMPLETED --> Deployment of package => ${{fromJson(inputs.package).package}}
          logMessage: COMPLETED Deployment of package